classdef tReferenceExact < matlab.unittest.TestCase
    % Reference tests asserting BIT-EXACT agreement with the original
    % matitk binary, for every fixture where mexitk reproduces the
    % captured output exactly.
    %
    % This list was produced by tools/classify_fixtures.m against the
    % post-Phase-3 tree (X/Y axis-convention fixes, SOT polarity/histogram
    % fix, FDM/FDMV reimplementation): every fixture NOT listed here either
    % deviates (see tReferenceBounded.m), is a rejection/accepts-more case
    % (see tReferenceRejections.m), or belongs to an opcode with its own
    % dedicated suite (FCA: tFcaReference.m; FOMT: tFomtReference.m; SWS:
    % tSwsReference.m). No tolerances: every assertion here is isequal on
    % the full array, plus an independent outputHash cross-check against
    % the fixture's own recorded hash (a second, hash-based confirmation
    % that a reshape or a coincidental near-match is not masking a real
    % difference).
    %
    % Re-run tools/classify_fixtures.m and update this list (and
    % tReferenceBounded.m / tReferenceRejections.m) after any change that
    % could move agreement with the original: an ITK upgrade, or a fix to
    % one of the opcodes covered here.
    %
    % SPDX-License-Identifier: BSD-3-Clause
    % Copyright (c) 2026, Seyed Yahya Shirazi <shirazi@ieee.org>
    % Swartz Center for Computational Neuroscience (SCCN),
    % Institute for Neural Computation (INC), UC San Diego.

    properties (TestParameter)
        exactFixture = { ...
            ... FF: axis-convention fix, all 12 captured fixtures exact.
            'ff_0_0_0_double', 'ff_0_0_0_uint8', 'ff_0_0_1_double', 'ff_0_0_1_uint8', ...
            'ff_0_1_0_double', 'ff_0_1_0_uint8', 'ff_1_0_0_double', 'ff_1_0_0_int32', ...
            'ff_1_0_0_single', 'ff_1_0_0_uint8', 'ff_1_0_1_double', 'ff_1_0_1_uint8', ...
            ... FD: axis-convention (SETDIRECTION swap) fix; every
            ... fixture where the original itself succeeded (uint8/int32
            ... are original-rejects-mexitk-accepts, see
            ... tReferenceRejections.m).
            'fd_0_0_double', 'fd_1_0_double', 'fd_1_0_single', 'fd_1_1_double', ...
            ... FMEDIAN: axis-convention fix, all 10 captured fixtures exact.
            'fmedian_r0_0_0_double', 'fmedian_r0_0_0_uint8', 'fmedian_r1_1_1_double', ...
            'fmedian_r1_1_1_int32', 'fmedian_r1_1_1_single', 'fmedian_r1_1_1_uint8', ...
            'fmedian_r1_1_3_double', 'fmedian_r2_2_2_double', 'fmedian_r2_2_2_uint8', ...
            'fmedian_r3_1_1_double', ...
            ... FMEAN: axis-convention fix (family-inferred; every captured
            ... fixture happens to be symmetric-radius, so this does not
            ... independently prove the swap for FMEAN -- see StatusNote in
            ... src/opcodes/fmean.cpp), all 8 captured fixtures exact.
            'fmean_r0_0_0_double', 'fmean_r0_0_0_uint8', 'fmean_r1_1_1_double', ...
            'fmean_r1_1_1_int32', 'fmean_r1_1_1_single', 'fmean_r1_1_1_uint8', ...
            'fmean_r2_2_2_double', 'fmean_r2_2_2_uint8', ...
            ... FVBIH: axis-convention fix; every fixture the original
            ... itself accepted (the foreground=300 uint8 fixture is a
            ... mexitk paramRange rejection, see tReferenceRejections.m).
            'fvbih_1_1_1_0_255_1_1_double', 'fvbih_1_1_1_0_255_1_1_int32', ...
            'fvbih_1_1_1_0_255_1_1_single', 'fvbih_1_1_1_0_255_1_1_uint8', ...
            'fvbih_1_1_1_0_300_1_1_double', 'fvbih_baseline_hole50_double', ...
            'fvbih_baseline_hole_double', 'fvbih_distinct_hole50_double', ...
            'fvbih_distinct_hole_double', ...
            ... SOT: polarity + histogram-range fix, all 6 captured
            ... fixtures exact across all four pixel types.
            'sot_128_double', 'sot_128_int32', 'sot_128_single', 'sot_128_uint8', ...
            'sot_polarity_128_double', 'sot_polarity_128_uint8', ...
            ... SNC: axis-convention fix; exact only for radius [1,1,1]
            ... and the base threshold fixtures -- other radii have a
            ... measured, axis-order-independent residual (see
            ... tReferenceBounded.m and src/opcodes/snc.cpp).
            'snc_1_1_1_20_60_255_seedS1_double', 'snc_1_1_1_20_60_255_seedS1_int32', ...
            'snc_1_1_1_20_60_255_seedS1_single', 'snc_1_1_1_20_60_255_seedS1_uint8', ...
            'snc_1_1_1_band_seedS1_double', ...
            ... FDM: reimplemented pipeline; exact for double/single/int32,
            ... a small measured residual remains for uint8 (see
            ... tReferenceBounded.m).
            'fdm_acc_bin_double', 'fdm_acc_lab_double', 'fdm_bin_double', ...
            'fdm_lab_double', 'fdm_raw_double', 'fdm_raw_int32', 'fdm_raw_single', ...
            ... FDMV: reimplemented pipeline; exact for single/int32. double
            ... has a floating-point-noise-level residual and uint8 uses a
            ... different (wrap, not rescale) formula with its own small
            ... residual -- both in tReferenceBounded.m.
            'fdmv_raw_int32', 'fdmv_raw_single', ...
            ... FBB, FBE, FGM: no code changes this phase, but reference
            ... fixtures now exist (captured in Phase 1) and every one
            ... matches exactly, so they are promoted alongside the
            ... opcodes this phase actually modified.
            'fbb_1_double', 'fbb_1_int32', 'fbb_1_single', 'fbb_1_uint8', ...
            'fbe_1_255_bin_double', 'fbe_1_255_bin_int32', 'fbe_1_255_double', ...
            'fbe_1_255_int32', 'fbe_1_255_single', 'fbe_1_255_uint8', ...
            'fbe_1_7_bin7_double', ...
            'fgm_raw_double', 'fgm_raw_int32', 'fgm_raw_single', 'fgm_raw_uint8', ...
            ... FBD: no code changes this phase; every fixture the
            ... original itself accepted matches exactly
            ... (ValueOverWhichDilateWillApply=300 on uint8 is a
            ... deliberate mexitk:paramRange rejection, see
            ... tReferenceRejections.m).
            'fbd_1_255_bin_double', 'fbd_1_255_double', 'fbd_1_255_int32', ...
            'fbd_1_255_single', 'fbd_1_255_uint8', 'fbd_1_300_double', ...
            'fbd_1_7_bin7_double', ...
            ... FBT: no code changes this phase; every fixture the
            ... original itself accepted matches exactly
            ... (upperThreshold=300 on uint8 and upperThreshold=1e39 on
            ... single are deliberate mexitk:paramRange rejections, see
            ... tReferenceRejections.m).
            'fbt_0_1_20_1e39_double', 'fbt_0_1_20_300_double', 'fbt_0_1_20_60_double', ...
            'fbt_0_1_20_60_int32', 'fbt_0_1_20_60_single', 'fbt_0_1_20_60_uint8', ...
            'fbt_5_9_1_88_double', ...
            ... SCT: no code changes this phase; every fixture where the
            ... original itself succeeded matches exactly (dimmax-seed and
            ... arg4-mismatch fixtures are original-rejects-mexitk-accepts,
            ... base0 is a mutual rejection -- both in
            ... tReferenceRejections.m).
            'sct_20_60_emptyseed_double', 'sct_20_60_fracseed_double', ...
            'sct_20_60_seedS1_double', 'sct_20_60_seedS1_int32', ...
            'sct_20_60_seedS1_single', 'sct_20_60_seedS1_uint8', 'sct_20_60_seed_double', ...
            'sct_band_seedS1_double', 'sct_band_seed_double', 'sct_off_minus1_double', ...
            'sct_off_plus1_double', 'sct_seed_50_70_14_double', 'sct_seed_70_50_14_double', ...
            'sct_wide_seedS1_double', ...
            ... SCC: no code changes this phase; every non-degenerate
            ... fixture matches exactly (the empty-seed fixture is a
            ... non-reproducible session-state artifact of the original,
            ... not a defined behaviour -- see tReferenceRejections.m;
            ... dimmax-seed is original-rejects-mexitk-accepts).
            'scc_1_5_100_seedS1_double', 'scc_2p5_5_100_seedS1_double', ...
            'scc_2p5_5_100_seedS1_int32', 'scc_2p5_5_100_seedS1_single', ...
            'scc_2p5_5_100_seedS1_uint8', 'scc_4_5_100_seedS1_double', ...
            'scc_off_minus1_double', 'scc_off_plus1_double', ...
            ... SIC: no code changes this phase; every fixture with two
            ... valid seed groups matches exactly (single-seed and
            ... dimmax-seed fixtures are rejection/accepts-more cases, see
            ... tReferenceRejections.m).
            'sic_20_255_seedS1S2_double', 'sic_20_255_seedS1S2_int32', ...
            'sic_20_255_seedS1S2_single', 'sic_20_255_seedS1S2_uint8', ...
            'sic_split_s1s2', 'sic_split_s1s2s3', 'sic_split_s2s1', ...
            ... FBL, FGMRG, FLS, FSN: bounded-deviation opcodes overall
            ... (see tReferenceBounded.m), but each has individual captured
            ... points that ARE bit-exact. tReferenceBounded.m's own Cases
            ... comments already claimed these were asserted here; PR
            ... review caught that they were not -- closing that gap.
            'fbl_2_10_int32', 'fbl_2_10_single', 'fbl_2_10_uint8', ...
            'fgmrg_2_int32', 'fgmrg_2_uint8', ...
            'fls_2_int32', ...
            'fsn_10_240_10_170_double', 'fsn_10_240_10_170_int32', ...
            'fsn_10_240_10_170_single', 'fsn_10_240_10_170_uint8', ...
            'fsn_10_240_10_44_uint8'};
    end

    methods (Test)
        function bitIdenticalToOriginal(tc, exactFixture)
            [fx, vin] = mexitkFixture(exactFixture);
            tc.assertTrue(fx.success, sprintf( ...
                '%s: fixture recorded success=false, does not belong in tReferenceExact', ...
                exactFixture));

            if isfield(fx, 'seedArg')
                got = mexitk(fx.opcode, fx.params, vin, cast([], class(vin)), fx.seedArg);
            else
                got = mexitk(fx.opcode, fx.params, vin);
            end

            tc.verifyClass(got, fx.outputClass, sprintf( ...
                '%s: output class does not match matitk', exactFixture));
            tc.verifyEqual(got, fx.output, sprintf( ...
                '%s: output is not bit-identical to matitk', exactFixture));

            recomputed = local_md5(got);
            tc.verifyEqual(recomputed, fx.outputHash, sprintf( ...
                '%s: recomputed outputHash %s does not match fixture outputHash %s', ...
                exactFixture, recomputed, fx.outputHash));
        end
    end
end
