classdef tReferenceBounded < matlab.unittest.TestCase
    % Reference tests pinning MEASURED, bounded disagreement with the
    % original matitk binary -- opcodes where mexitk runs the same ITK
    % filter with the same parameters, but the output is not bit-identical
    % because ITK's own numerics evolved between 2.4 (the original's build)
    % and 5.x, or because the original itself used a lower-precision
    % internal representation for one pixel type.
    %
    % Every (RMS, max-abs) pair below is read off an actual comparison run
    % (tools/classify_fixtures.m against the post-Phase-3 tree), never
    % estimated or tuned to make the suite green. Per project policy: if a
    % bound is ever hit, the correct response is to investigate why
    % agreement with the original moved and update docs/COMPATIBILITY.md,
    % never to raise the number. FCA and SWS have their own dedicated
    % suites (tFcaReference.m, tSwsReference.m) and are not repeated here.
    % SWS and FAAB are deliberately excluded even though fixtures exist for
    % FAAB: their measured disagreement (RMS in the hundreds) is not a
    % useful bound to pin, only a fact to document -- see
    % docs/COMPATIBILITY.md, "SWS and FAAB: not bounded".
    %
    % SPDX-License-Identifier: BSD-3-Clause
    % Copyright (c) 2026, Seyed Yahya Shirazi <shirazi@ieee.org>
    % Swartz Center for Computational Neuroscience (SCCN),
    % Institute for Neural Computation (INC), UC San Diego.

    properties (TestParameter)
        % One parameterization per row of Cases below, keyed by fixture
        % name (each name is unique and a valid MATLAB identifier, so it
        % doubles as the test-instance name in output). Parameterized
        % rather than a single method looping over Cases: a loop means one
        % bad fixture aborts every case after it in the same test run,
        % where TestParameter runs each case as its own independent test.
        boundedCase = tReferenceBounded.caseParams();
    end

    properties (Constant)
        % opcode, fixture name, measured RMS, measured max-abs.
        Cases = { ...
            ... FDG / FGA: DiscreteGaussianImageFilter numerics moved
            ... between 2.4 and 5.x, same as FCA's own diffusion filter.
            ... FGA is implemented as a deliberate duplicate of FDG (see
            ... docs/COMPATIBILITY.md); their measured numbers are
            ... identical at matching parameters, confirming the alias.
            'FDG', 'fdg_1_5_double',     5.51639e-15, 5.68434e-14; ...
            'FDG', 'fdg_4_5_double',     4.12776e-03, 3.01644e-02; ...
            'FDG', 'fdg_10_5_double',    1.21742e-03, 7.90703e-03; ...
            'FDG', 'fdg_4_5_single',     4.12776e-03, 3.01628e-02; ...
            'FDG', 'fdg_4_5_int32',      2.86817e-01, 2.0;         ...
            'FDG', 'fdg_id_1_5_double',  5.51639e-15, 5.68434e-14; ...
            'FDG', 'fdg_id_4_5_double',  4.12776e-03, 3.01644e-02; ...
            'FDG', 'fdg_id_10_5_double', 1.21742e-03, 7.90703e-03; ...
            'FGA', 'fga_4_5_double',     4.12776e-03, 3.01644e-02; ...
            'FGA', 'fga_4_5_single',     4.12776e-03, 3.01628e-02; ...
            'FGA', 'fga_4_5_int32',      2.86817e-01, 2.0;         ...
            'FGA', 'fga_id_1_5_double',  5.51639e-15, 5.68434e-14; ...
            'FGA', 'fga_id_4_5_double',  4.12776e-03, 3.01644e-02; ...
            'FGA', 'fga_id_10_5_double', 1.21742e-03, 7.90703e-03; ...
            ...
            ... FGAD: GradientAnisotropicDiffusionImageFilter, same
            ... upstream-numerics story as FCA.
            'FGAD', 'fgad_2_0p0625_40_double',  4.74279e-05, 6.82498e-04; ...
            'FGAD', 'fgad_40_0p0625_2_double',  1.33617e-02, 6.05228e-01; ...
            'FGAD', 'fgad_5_0p0625_10_double',  8.20297e-04, 9.49829e-03; ...
            'FGAD', 'fgad_5_0p0625_3_double',   5.39286e-03, 7.36632e-02; ...
            'FGAD', 'fgad_5_0p0625_3_int32',    1.26501,     5.0;         ...
            'FGAD', 'fgad_5_0p0625_3_single',   6.57574e-03, 8.95309e-02; ...
            'FGAD', 'fgad_5_0p0625_3_uint8',    11.7184,     55.0;        ...
            'FGAD', 'fgad_5_10_0p0625_double',  3.49656e-01, 1.75066e+01; ...
            ...
            ... FCF: CurvatureFlowImageFilter, same story.
            'FCF', 'fcf_5_0p0625_double',   8.76748e-16, 4.26326e-14; ...
            'FCF', 'fcf_10_0p0625_double',  1.23338e-15, 9.94760e-14; ...
            'FCF', 'fcf_20_0p0625_double',  1.68409e-15, 1.70530e-13; ...
            'FCF', 'fcf_10_0p0625_single',  7.45584e-07, 5.34058e-05; ...
            'FCF', 'fcf_10_0p0625_int32',   1.721,       21.0;        ...
            'FCF', 'fcf_10_0p0625_uint8',   7.27783,     130.0;       ...
            ...
            ... FBL: BilateralImageFilter. double's own residual is at
            ... the floating-point noise floor (1e-13-1e-12); int32/
            ... single/uint8 are bit-exact (see tReferenceExact.m).
            'FBL', 'fbl_2_10_double',  9.54532e-14, 1.09424e-12; ...
            'FBL', 'fbl_10_2_double',  5.03596e-13, 5.17275e-12; ...
            'FBL', 'fbl_5_5_double',   4.50544e-13, 3.92220e-12; ...
            ...
            ... FSN: SigmoidImageFilter. One fixture at the floating-point
            ... noise floor; the other five captured fixtures are
            ... bit-exact (see tReferenceExact.m).
            'FSN', 'fsn_10_240_10_44_double', 1.73979e-15, 2.84217e-14; ...
            ...
            ... FVMI: two-filter Hessian-vesselness pipeline; both stages'
            ... internal numerics moved between 2.4 and 5.x.
            'FVMI', 'fvmi_1_0p5_2_double',  0.513911, 9.76872;  ...
            'FVMI', 'fvmi_1_2_0p5_double',  0.497462, 10.0506;  ...
            'FVMI', 'fvmi_3_0p5_2_double',  0.0827188, 1.18877; ...
            'FVMI', 'fvmi_1_0p5_2_single',  0.513911, 9.76872;  ...
            'FVMI', 'fvmi_1_0p5_2_int32',   0.493737, 10.0;     ...
            'FVMI', 'fvmi_1_0p5_2_uint8',   0.493737, 10.0;     ...
            ...
            ... FGMRG: GradientMagnitudeRecursiveGaussianImageFilter;
            ... recursive-Gaussian numerics moved between 2.4 and 5.x.
            ... int32/uint8 at sigma=2 are bit-exact (see
            ... tReferenceExact.m); every other captured combination has a
            ... floating-point-scale residual.
            'FGMRG', 'fgmrg_1_double', 2.73366e-07, 5.43344e-06; ...
            'FGMRG', 'fgmrg_2_double', 1.32290e-07, 1.85020e-06; ...
            'FGMRG', 'fgmrg_4_double', 7.13001e-08, 9.00417e-07; ...
            'FGMRG', 'fgmrg_2_single', 1.16793e-07, 1.90735e-06; ...
            ...
            ... FLS: LaplacianRecursiveGaussianImageFilter, same story;
            ... uint8's clamp-back export (deviation 8) makes its own
            ... residual much larger since the underlying signed field
            ... saturates on export. int32 at sigma=2 is bit-exact (see
            ... tReferenceExact.m).
            'FLS', 'fls_1_double', 2.10075e-07, 3.81470e-06; ...
            'FLS', 'fls_2_double', 4.50375e-08, 9.53674e-07; ...
            'FLS', 'fls_4_double', 7.90163e-09, 2.38419e-07; ...
            'FLS', 'fls_2_single', 4.50375e-08, 9.53674e-07; ...
            'FLS', 'fls_2_uint8',  98.6939,     255.0;       ...
            ...
            ... FDM: reimplemented pipeline (Epic 2 Phase 3). double/
            ... single/int32 are bit-exact (see tReferenceExact.m); uint8
            ... alone has a small residual, likely reflecting a
            ... lower-precision internal distance representation in the
            ... original's own uint8 instantiation (see
            ... src/opcodes/fdm.cpp).
            'FDM', 'fdm_raw_uint8',   0.217891, 6.0; ...
            'FDM', 'fdm_bin_uint8',   0.205432, 6.0; ...
            'FDM', 'fdm_lab_uint8',   0.205432, 6.0; ...
            ...
            ... FDMV: reimplemented pipeline. single/int32 are bit-exact
            ... (see tReferenceExact.m). double has a floating-point
            ... op-order residual right at double precision's own limit
            ... (persists under an alternative op ordering too -- see
            ... src/opcodes/fdm.cpp). uint8 uses a direct-cast wraparound
            ... formula, not a rescale, with its own small residual
            ... consistent with ITK 2.4-vs-5.4 Voronoi tie-break
            ... divergence at equidistant background voxels.
            'FDMV', 'fdmv_raw_double',     3.34842e-12, 7.27596e-12; ...
            'FDMV', 'fdmv_bin_double',     3.14089e-12, 7.27596e-12; ...
            'FDMV', 'fdmv_lab_double',     3.14089e-12, 7.27596e-12; ...
            'FDMV', 'fdmv_acc_bin_double', 3.14089e-12, 7.27596e-12; ...
            'FDMV', 'fdmv_acc_lab_double', 3.14089e-12, 7.27596e-12; ...
            'FDMV', 'fdmv_raw_uint8',      11.4355,     255.0;       ...
            'FDMV', 'fdmv_bin_uint8',      8.62219,     255.0;       ...
            'FDMV', 'fdmv_lab_uint8',      8.62219,     255.0;       ...
            ...
            ... SNC: axis-convention fix (Epic 2 Phase 3) makes radius
            ... [1,1,1] and the base threshold fixtures bit-exact (see
            ... tReferenceExact.m), but NeighborhoodConnectedImageFilter
            ... itself diverges from the original for other radii,
            ... independent of axis order: snc_r0_band (radius [0,0,0],
            ... symmetric, so the axis swap is a total no-op there) still
            ... deviates substantially, proving a separate upstream-
            ... algorithm difference, the same class of issue as FCA/SWS.
            'SNC', 'snc_r0_band_seedS1_double', 73.321,  255.0; ...
            'SNC', 'snc_r2_band_seedS1_double', 1.75694, 255.0; ...
            'SNC', 'snc_rx_wide_seedS1_double', 47.1001, 255.0; ...
            'SNC', 'snc_rz_wide_seedS1_double', 62.2875, 255.0};
    end

    methods (Static)
        function s = caseParams()
            % Converts the Cases table above into the struct TestParameter
            % needs: one field per row, field name == fixture name, field
            % value == a struct carrying that row's own (opcode, name,
            % rmsMeasured, maxMeasured).
            rows = tReferenceBounded.Cases;
            s = struct();
            for i = 1:size(rows, 1)
                name = rows{i, 2};
                s.(name) = struct('opcode', rows{i, 1}, 'name', name, ...
                    'rmsMeasured', rows{i, 3}, 'maxMeasured', rows{i, 4});
            end
        end
    end

    methods (Test)
        function deviationMatchesDocumentedBound(tc, boundedCase)
            opcode = boundedCase.opcode;
            name = boundedCase.name;
            rmsMeasured = boundedCase.rmsMeasured;
            maxMeasured = boundedCase.maxMeasured;

            [fx, vin] = mexitkFixture(name);
            tc.assertTrue(fx.success, sprintf( ...
                '%s: fixture recorded success=false', name));
            if isfield(fx, 'seedArg')
                got = mexitk(opcode, fx.params, vin, cast([], class(vin)), fx.seedArg);
            else
                got = mexitk(opcode, fx.params, vin);
            end

            e = abs(double(got(:)) - double(fx.output(:)));
            rms = sqrt(mean(e .^ 2));
            mx = max(e);

            % 10% headroom over the measured value: enough to absorb
            % platform floating-point ordering, far too tight to hide
            % a real behavioural change. A floor keeps this meaningful
            % for measurements at (or near) zero.
            rmsCeiling = max(rmsMeasured * 1.1, rmsMeasured + 1e-12);
            maxCeiling = max(maxMeasured * 1.1, maxMeasured + 1e-9);
            tc.verifyLessThan(rms, rmsCeiling, sprintf( ...
                '%s (%s): RMS deviation %.6g exceeds documented %.6g', ...
                name, opcode, rms, rmsMeasured));
            tc.verifyLessThan(mx, maxCeiling, sprintf( ...
                '%s (%s): max deviation %.6g exceeds documented %.6g', ...
                name, opcode, mx, maxMeasured));

            % Guard the other direction too, but only for measurements
            % well above the floating-point noise floor: a value
            % already near double precision's own limit (< 1e-8) can
            % legitimately shift by a platform-dependent factor of 2-3
            % without indicating any real change in agreement.
            if rmsMeasured > 1e-8
                tc.verifyGreaterThan(rms, rmsMeasured * 0.1, sprintf( ...
                    ['%s (%s): now agrees with matitk far better than ' ...
                     'documented (RMS %.6g vs %.6g); re-baseline and ' ...
                     'update docs/COMPATIBILITY.md'], name, opcode, rms, rmsMeasured));
            end
        end
    end
end
